module.exports= {
    SIGN_UP:"SIGN_UP",
    SIGN_IN:"SIGN_IN",
    USER_CONNECTED:"USER_CONNECTED",
    USER_DISCONNECTED:"USER_DISCONNECTED",
    VERIFY_USER:"VERIFY_USER",    
    LOGOUT:"LOGOUT"
}